"""add indexed_at

Revision ID: 51ff4c3d8cc6
Revises: 2084cacdb5b6
Create Date: 2026-07-13 11:59:33.068159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51ff4c3d8cc6'
down_revision: Union[str, Sequence[str], None] = '2084cacdb5b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('indexed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repositories', 'indexed_at')
    # ### end Alembic commands ###
